### ISSUE TITLE
[FEAT] 후원글 등록 서버 API 연결

### ISSUE THREAD

**Issue by ej070961** [K-Hackathon-Fledge/Fledge-Front#16]
## ✅ Description
- 후원글 등록 기능 마무리 및 서버  API 연결 
## ✔️ TODO
- [x] 카테고리, 인증방식 id값 수정
- [x] 이미지 업로드 삭제 기능 추가
- [x] 계좌번호 입력 컴포넌트
- [x] 서버 api 연결
