### ISSUE TITLE
[FEAT] 메인페이지 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by seokkkkkk** [K-Hackathon-Fledge/Fledge-Front#2]
## ✅ Description
- 메인페이지 컴포넌트 UI 구현
## ✔️ TODO
- [x] 페이지 상단 내비게이션 바 구현
- [x] 배너 슬라이더 구현
- [x] 챌린지 컴포넌트 구현
- [x] 챌린지 리스트 구현
- [x] 멘토링 컴포넌트 구현
- [x] 정보공유 컴포넌트 구현
- [x] 정보공유 리스트 구현
- [x] 푸터 구현
## ETC
