### ISSUE TITLE
[FEAT] 챌린지 페이지 UI 구성

### ISSUE THREAD

**Issue by seokkkkkk** [K-Hackathon-Fledge/Fledge-Front#26]
## ✅ Description
챌린지 페이지 UI 구성 및 컴포넌트 생성

## ✔️ TODO
- [x] 페이지 UI 구성
- [x] 베스트 챌린저 컴포넌트
- [x] 챌린지 컴포넌트 그리드 구성
