### ISSUE TITLE
챌린지 상세 페이지 UI, AP

### ISSUE THREAD

**Issue by seokkkkkk** [K-Hackathon-Fledge/Fledge-Front#50]
## ✅ Description
챌린지 상세 페이지에 대한 UI 구성과 API 연결
## ✔️ TODO
- [x] 페이지 상단 챌린지 정보 UI
- [x] 함께하는 챌린저 UI
- [x] 인증 내역 UI
- [x] 다른 챌린지 추천 UI
- [x] 챌린지 참여 모달 UI
- [x] 챌린지 포기 모달 UI
- [x] 챌린지 인증 모달 UI
- [x] 페이지 상단 챌린지 정보 API 연결
- [x] 함께하는 챌린저 API 연결
- [x] 인증 내역 API 연결
- [x] 다른 챌린지 추천 API 연결
- [x] 챌린지 참여 API 연결
- [x] 챌린지 인증 API 연결
